
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data-bazari:/var/lib/postgresql/data


  redis:
    image: redis:6
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data-bazari:/data
      
  redis-commander:
    image: rediscommander/redis-commander:latest
    ports:
      - "8081:8081"
    environment:
      REDIS_HOSTS: local:redis:6379
    

  flask-app:
    build: .
    depends_on:
      - postgres
      - redis
    environment:
      DB_HOST: postgres
      DB_NAME: bazari
      DB_USER: postgres
      DB_PASSWORD: postgres
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - "8000:8000"


volume:
  postgres-data-bazari:
  redis-data-bazari: