version: '3.8'  # You can specify a version that suits your needs

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"  # Expose PostgreSQL on host port 5432
    volumes:
      - postgres-data-bazari:/var/lib/postgresql/data  # Use named volume for persistence

  redis:
    image: redis:6
    ports:
      - "6379:6379"  # Expose Redis on host port 6379
    volumes:
      - redis-data-bazari:/data  # Use named volume for persistence

  redis-commander:
    image: rediscommander/redis-commander:latest
    ports:
      - "8081:8081"  # Expose Redis Commander on host port 8081
    environment:
      REDIS_HOSTS: local:redis:6379  # Connection to Redis service

  flask-app:
    build: .  # Build the Flask app from the Dockerfile in the current directory
    depends_on:
      - postgres  # Wait for PostgreSQL to be available
      - redis  # Wait for Redis to be available
    environment:
      DB_HOST: postgres  # Use the service name to connect to PostgreSQL
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      REDIS_HOST: redis  # Use the service name to connect to Redis
      REDIS_PORT: 6379
    ports:
      - "8000:8000"  # Expose the Flask app on host port 8000

volumes:
  postgres-data-bazari:  # Named volume for PostgreSQL data
  redis-data-bazari:  # Named volume for Redis data
